name: 'Collect Stats'

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'

env:
  node_version: 16

jobs:
  stat:
    if: github.repository == 'snowpackjs/astro'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v1
        with:
          version: 16
      - run: yarn install --frozen-lockfile --ignore-engines --ignore-scripts
      - run: node scripts/stats/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[ci] collect stats'
          branch: ${{ github.head_ref }}
